import { Routes } from '@angular/router';
import { Feed } from './components/feed/feed';
import { AdminPanel } from './components/admin-panel/admin-panel';
import { Offerings } from './components/offerings/offerings';
import { SocialLinks } from './components/social-links/social-links';
import { Churches } from './components/churches/churches';
import { Contact } from './components/contact/contact';
import { CoursesPage } from './components/courses-page/courses-page';
import { GalleryPage } from './components/gallery-page/gallery-page';
import { PrayerPage } from './components/prayer-page/prayer-page';
import { AboutUs } from './components/about-us/about-us';
import { Serve } from './components/serve/serve';
import { CalendarPage } from './components/calendar/calendar';
import { MinistrySchedulePage } from './components/ministry-schedule/ministry-schedule';
import { Profile } from './components/profile/profile';
import { SmallGroups } from './components/small-groups/small-groups';
import { MembersList } from './components/members-list/members-list';

export const routes: Routes = [
  { path: '', component: AboutUs },
  { path: 'feed', component: Feed },
  { path: 'serve', component: Serve },
  { path: 'profile', component: Profile },
  { path: 'admin', component: AdminPanel },
  { path: 'small-groups', component: SmallGroups },
  { path: 'members-list', component: MembersList },
  { path: 'offerings', component: Offerings },
  { path: 'social', component: SocialLinks },
  { path: 'churches', component: Churches },
  { path: 'contact', component: Contact },
  { path: 'courses', component: CoursesPage },
  { path: 'gallery', component: GalleryPage },
  { path: 'prayer', component: PrayerPage },
  { path: 'calendar', component: CalendarPage },
  { path: 'ministry-schedule', component: MinistrySchedulePage },
  { path: '**', redirectTo: '' }
];
